export interface Goal {
  id?: string; // UUID, generated by Supabase, optional on creation
  user_id: string; // UUID, links to auth.users
  description: string;
  type: 'monthly' | 'annual';
  month: number | null; // 1-12 for monthly, null for annual
  year: number;
  is_completed: boolean;
  order_index: number;
  created_at?: string; // Timestamp, managed by Supabase
  updated_at?: string; // Timestamp, managed by Supabase
  dimension: import('../types').Dimension;
} 